version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64
 
configuration:
  - Debug
  - Release

before_build:
  - md build
  - cd build
  - cmake .. -G "Visual Studio 15 2017 Win64"

build:
  project: $(APPVEYOR_BUILD_FOLDER)\build\GTestAllureUtilities.sln
  
for:
  -
    matrix:
      only:
        - configuration: Debug
    test_script:
      - cd ..
      - cd bin
      - cd Debug
      - UnitTest.exe
  -
    matrix:
      only:
        - configuration: Release
    test_script:
      - cd ..
      - cd bin
      - cd Release
      - UnitTest.exe