dist: trusty
language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

  # Download and install recent cmake
  - |
    if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.13/cmake-3.13.2-Linux-x86_64.tar.gz"
      sudo mkdir -p ${DEPS_DIR}/cmake
      sudo wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi

script:    
  - g++ --version
  - mkdir -p build
  - cd build
  - cmake .. 
  - make
  - cd test
  - cd UnitTest
  - ctest